Adding running command in cluster utility to common
medik8s/common pull request #19
Opened 2024-01-25 09:53 UTC by mshitrit

2024-01-25 10:41 UTC, clobrano requested changes

2024-01-25 10:41 UTC, clobrano commented on pkg/command/command.go
> +	err = exec.Stream(remotecommand.StreamOptions{
It seems that `exec.Stream` is deprecated
https://pkg.go.dev/k8s.io/client-go@v0.26.3/tools/remotecommand#Executor.Stream

2024-01-25 10:41 UTC, slintes commented
/lgtm
/hold

I think Carlo was looking as well :)

2024-01-25 10:51 UTC, clobrano commented
/lgtm 
Giving a chance to get more reviews, feel free to unhold
/hold

2024-01-25 11:15 UTC, mshitrit commented
/unhold

2024-01-25 11:45 UTC, mshitrit commented
/retest

2024-01-25 12:46 UTC, mshitrit commented
/test ?

2024-01-25 12:46 UTC, mshitrit commented
/test lint

2024-01-26 08:59 UTC, slintes commented
/test all

2024-01-26 09:07 UTC, merged